# Generated by Django 5.1.4 on 2026-01-21 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_number', models.IntegerField()),
                ('timestamp_seconds', models.FloatField()),
                ('image_path', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['video', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('fps', models.FloatField(default=30.0)),
                ('total_frames', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject_id', models.CharField(blank=True, help_text='Anonymous subject identifier', max_length=100)),
                ('recording_context', models.CharField(blank=True, help_text='e.g., baseline, heel_lance, immunization, post_operative', max_length=100)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facial_expression', models.IntegerField(choices=[(0, 'Relaxed muscles - Restful face, neutral expression'), (1, 'Grimace - Tight facial muscles, furrowed brow, chin, jaw')])),
                ('cry', models.IntegerField(choices=[(0, 'No cry - Quiet, not crying'), (1, 'Whimper - Mild moaning, intermittent'), (2, 'Vigorous cry - Loud scream, shrill, continuous')])),
                ('breathing_pattern', models.IntegerField(choices=[(0, 'Relaxed - Usual pattern for this infant'), (1, 'Change in breathing - Irregular, faster than usual, gagging, breath holding')])),
                ('arms', models.IntegerField(choices=[(0, 'Relaxed/Restrained - No muscular rigidity, occasional random movements'), (1, 'Flexed/Extended - Tense, straight arms, rigid and/or rapid extension, flexion')])),
                ('legs', models.IntegerField(choices=[(0, 'Relaxed/Restrained - No muscular rigidity, occasional random movements'), (1, 'Flexed/Extended - Tense, straight legs, rigid and/or rapid extension, flexion')])),
                ('state_of_arousal', models.IntegerField(choices=[(0, 'Sleeping/Awake - Quiet, peaceful, settled'), (1, 'Fussy - Alert, restless, thrashing')])),
                ('annotator_id', models.CharField(help_text='Anonymous annotator identifier', max_length=100)),
                ('confidence', models.CharField(choices=[('high', 'High - Clear indicators'), ('medium', 'Medium - Some uncertainty'), ('low', 'Low - Difficult to assess')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any observations or difficulties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.frame')),
            ],
            options={
                'ordering': ['frame__video', 'frame__frame_number', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.video'),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('video', 'frame_number')},
        ),
    ]
